'use strict';
(()=>{
if(new URLSearchParams(location.search).get('simple')!=='1')return;
document.body.classList.add('delivery-compact');
const root=document.createElement('div');root.id='demoRoot';root.innerHTML=`<header id="demoTop"><h1>钢琴手套</h1><button id="demoConnection">未连接 · 重连</button><select id="demoPort" aria-label="选择手套串口"><option value="">寻找 USB 串口</option></select><button id="demoFlash">一键烧录</button><button id="demoStop">■ 停止</button></header><nav id="demoTabs"><button id="demoTabCalibration" class="active">校准与动作</button><button id="demoTabSongs">曲目展示</button></nav><section id="demoCalibration" class="demo-panel"></section><section id="demoSongs" class="demo-panel" hidden></section><footer id="demoFoot"><span id="demoNotice">正在读取手套状态…</span><span id="demoVersion"></span></footer><dialog id="demoFirmwareDialog"><button id="demoFirmwareClose" aria-label="关闭烧录窗口">关闭</button><h2 id="demoFirmwareTitle">烧录固件</h2><progress id="demoFirmwareProgress" max="100" value="0"></progress><p id="demoFirmwareStatus">等待开始</p><details><summary>查看日志</summary><pre id="demoFirmwareLog"></pre></details></dialog>`;document.body.append(root);
const q=id=>document.getElementById(id);let bridge={},firmware={},requesting=false,polling=false,error='',chosen='',switching=false,lastIdentity=null,attemptedIdentity=null,identificationError='',lastProbeAt=0,identifying=false,nextReconnectAt=0,reconnectFailures=0;
const busy=()=>requesting||firmware.busy;const active=()=>S.playing||window.pianoStrictTrainingActive?.()||window.deliveryDemoBusy?.();
window.pianoFirmwareBusy=busy;
function notice(text){q('demoNotice').textContent=text;}window.deliveryDemoNotice=notice;
function tab(songs){q('demoCalibration').hidden=songs;q('demoSongs').hidden=!songs;q('demoTabCalibration').classList.toggle('active',!songs);q('demoTabSongs').classList.toggle('active',songs);}
document.addEventListener('delivery:import',()=>tab(true));q('demoTabCalibration').onclick=()=>tab(false);q('demoTabSongs').onclick=()=>tab(true);
async function api(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4000);try{const r=await fetch(path,body===undefined?{cache:'no-store',signal:controller.signal}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||j.msg||`请求失败 ${r.status}`);return j;}finally{clearTimeout(timer);}}
function paint(){const isBusy=busy(),connected=!!bridge.connected&&!!S.info.ver,unknown=!!bridge.connected&&!connected&&attemptedIdentity===lastIdentity;q('demoConnection').textContent=connected?'已连接 '+bridge.port:unknown?bridge.port+'已连接 · 固件未识别':bridge.connected?'连接中 '+bridge.port:switching?'正在自动连接':'等待 USB · 自动连接';if(unknown)notice('串口已连接，固件未识别：'+(bridge.error||bridge.last_error||identificationError||'未收到有效应答，正在定期重新识别。'));q('demoConnection').classList.toggle('connected',connected);q('demoConnection').classList.toggle('warning',unknown);q('demoPort').classList.toggle('connected',!!bridge.connected&&q('demoPort').value===bridge.port);q('demoConnection').disabled=isBusy||switching||active();q('demoPort').disabled=isBusy||switching||active();q('demoFlash').disabled=isBusy||active()||!q('demoPort').value||firmware.available===false;q('demoVersion').textContent=connected?'设备 v'+S.info.ver:'';q('demoFirmwareTitle').textContent='烧录固件'+(firmware.version?' v'+firmware.version:'');const labels={idle:'等待操作',running:'处理中',built:'编译完成，未烧录',verified:'烧录完成，回读已验证',failed:'烧录失败',written_unverified:'已写入，回读未验证',queued:'准备中',stop:'正在停止任务',build:'正在编译',identify:'识别主控',write:'正在写入',verify:'校验写入内容',readback:'读取主控状态',complete:'完成'};q('demoFirmwareProgress').value=Math.max(0,Math.min(100,Number(firmware.progress)||0));let text=labels[firmware.busy?firmware.phase:firmware.state]||firmware.phase||'等待操作';if(firmware.error)text+='\n'+firmware.error;if(error)text+='\n'+error;if(firmware.stopConfirmed===true)text+='\n烧录前停止已确认。';if(firmware.verified===true)text+='\n未启动动作，可关闭窗口。';else if(firmware.written===true)text+='\n请确认主控回读结果，写入不代表验证通过。';q('demoFirmwareStatus').textContent=text;q('demoFirmwareLog').textContent=Array.isArray(firmware.log)?firmware.log.join('\n'):String(firmware.log||'');}
async function identifyOnce(st,identity){const now=Date.now();if(identifying||busy()||active()||attemptedIdentity===identity&&now-lastProbeAt<(S.info.ver?10000:5000))return;identifying=true;attemptedIdentity=identity;lastProbeAt=now;identificationError='';T.attachBridge(st);stopPolling();paint();try{const reply=await api('/api/send',{cmd:'INFO',timeoutMs:650,quietMs:25});if(lastIdentity!==identity)return;const line=reply.lines?.find(l=>/^OK INFO\s/.test(l));if(line){const recovered=!S.info.ver;S.info=kv(line);S.needArm=true;refreshChips();if(recovered)notice('已自动连接 '+st.port+'，固件识别正常。');}else{S.info={};identificationError=reply.lines?.find(l=>/^ERR\b/.test(l))||'未收到有效 INFO 应答';}}catch(e){if(lastIdentity===identity){S.info={};identificationError=e.message;}}finally{identifying=false;paint();}}
async function syncIdentity(st){const identity=st.connected?String(st.port)+':'+String(st.connectedAt):'';if(lastIdentity===identity){T._noteBridge(st);if(st.connected)await identifyOnce(st,identity);return;}const previous=lastIdentity;lastIdentity=identity;attemptedIdentity=null;identificationError='';T._q.length=0;if(T._qTimer){clearTimeout(T._qTimer);T._qTimer=null;}S.playing=false;if(S.raf)cancelAnimationFrame(S.raf);S.raf=null;stopPosPoll();silence();stopPolling();T.detachBridge();T._noteBridge(st);S.info={};S.slots={};S.needArm=true;if(window.pianoStrictExecutor?.active)window.pianoStrictExecutor.cancelled=true;document.dispatchEvent(new CustomEvent('delivery:identitychange',{detail:{previous,identity,state:st}}));refreshChips();if(st.connected)await identifyOnce(st,identity);}
async function autoReconnect(st){if(st.connected){reconnectFailures=0;nextReconnectAt=0;return;}if(busy()||active()||switching||Date.now()<nextReconnectAt)return;const ports=(st.ports||[]).filter(p=>p.eligible===true||p.candidate===true);const target=ports.find(p=>p.device===chosen)||ports[0];if(!target)return;switching=true;nextReconnectAt=Date.now()+2000;paint();try{const result=await api('/api/connect',{port:target.device,baud:115200});chosen=target.device;bridge=await api('/api/status');window.deliveryDemoState=bridge;reconnectFailures=0;if(!bridge.connected)throw Error('串口尚未就绪');await syncIdentity(bridge);notice('串口已自动连接，不自动启动动作。');}catch(e){reconnectFailures++;nextReconnectAt=Date.now()+Math.min(10000,2000*reconnectFailures);notice('正在自动重连：'+e.message);}finally{switching=false;paint();}}
async function refresh(){if(polling)return;polling=true;try{const [st,fw]=await Promise.all([api('/api/status'),api('/api/firmware')]);bridge=st;firmware=fw;window.deliveryDemoState=st;const ports=(fw.ports||[]).filter(p=>p.eligible!==false&&(/CP210/i.test(p.label||p.description||'')||p.vid===4292));const current=chosen||st.port||q('demoPort').value;const options=ports.map(p=>new Option(p.port||p.device,p.port||p.device));q('demoPort').replaceChildren(...options);if(options.some(o=>o.value===current))q('demoPort').value=current;else if(options.length)q('demoPort').selectedIndex=0;chosen=q('demoPort').value;paint();await syncIdentity(st);await autoReconnect(st);document.dispatchEvent(new CustomEvent('delivery:state',{detail:st}));paint();}catch(e){notice('读取状态失败：'+e.message);}finally{polling=false;}}
async function connect(){if(busy()||active())return;switching=true;error='';paint();try{await api('/api/connect',{port:q('demoPort').value,baud:115200});notice('串口已切换，不自动启动动作。');await refresh();}catch(e){notice('连接失败：'+e.message);}finally{switching=false;paint();}}
q('demoConnection').onclick=()=>refresh();q('demoPort').onchange=()=>{chosen=q('demoPort').value;connect();};
q('demoStop').onclick=async()=>{try{if(busy()){T._q.length=0;if(T._qTimer){clearTimeout(T._qTimer);T._qTimer=null;}notice(firmware.stopConfirmed===true?'页面队列已清除；烧录前停止已确认，写入继续。':'页面队列已清除；主控维护中，硬件停止状态请以烧录日志为准。');return;}if(window.deliveryDemoStop)await window.deliveryDemoStop();T._q.length=0;if(T._qTimer){clearTimeout(T._qTimer);T._qTimer=null;}stopPlay(true);notice('已请求停止，不自动恢复。');}catch(e){notice('停止未确认：'+e.message);}};
q('demoFlash').onclick=async()=>{if(busy()||active()||!q('demoPort').value)return;requesting=true;error='';q('demoFirmwareDialog').show();firmware={...firmware,state:'running',phase:'queued',progress:0,written:false,verified:false,error:''};paint();try{T._q.length=0;if(T._qTimer){clearTimeout(T._qTimer);T._qTimer=null;}stopPlay(true);await api('/api/firmware/flash',{port:q('demoPort').value});await refresh();}catch(e){error=e.message;firmware.state='failed';}finally{requesting=false;paint();}};
q('demoFirmwareClose').onclick=()=>q('demoFirmwareDialog').close();
document.addEventListener('click',e=>{if(!busy())return;const c=e.target.closest('button,input,select');if(c&&root.contains(c)&&!['demoStop','demoFirmwareClose'].includes(c.id)&&!q('demoFirmwareDialog').contains(c)){e.preventDefault();e.stopImmediatePropagation();}},true);
setInterval(refresh,1200);refresh();
})();
