const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../delivery-shell.js'),'utf8');
const identify=source.slice(source.indexOf('async function identifyOnce('),source.indexOf('async function syncIdentity('));
const reconnect=source.slice(source.indexOf('async function autoReconnect('),source.indexOf('async function refresh('));
function setup(reply){let calls=0,attached=0,painted=0,now=10000;const context={attemptedIdentity:null,lastIdentity:'COM3:1',lastProbeAt:0,identifying:false,firmware:{busy:false},busy:()=>false,active:()=>false,Date:{now:()=>now},identificationError:'',S:{info:{},needArm:false},T:{attachBridge(){attached++;}},stopPolling(){},paint(){painted++;},refreshChips(){},notice(){},kv:s=>Object.fromEntries([...s.matchAll(/(\w+)=([^\s]+)/g)].map(x=>[x[1],x[2]])),api:async(path,body)=>{calls++;assert.equal(path,'/api/send');assert.deepEqual(JSON.parse(JSON.stringify(body)),{cmd:'INFO',timeoutMs:650,quietMs:25});return reply;}};vm.createContext(context);vm.runInContext(identify,context);return {context,advance:ms=>now+=ms,stats:()=>({calls,attached,painted})};}
test('serial renders before INFO and failed recognition retries at 5 seconds without reopening port',async()=>{let resolve;const s=setup(new Promise(r=>resolve=r));const run=s.context.identifyOnce({port:'COM3'},'COM3:1');assert.deepEqual(s.stats(),{calls:1,attached:1,painted:1});resolve({lines:['ERR UNKNOWN_COMMAND']});await run;await s.context.identifyOnce({},'COM3:1');assert.equal(s.stats().calls,1);s.advance(5000);await s.context.identifyOnce({},'COM3:1');assert.equal(s.stats().calls,2);assert.equal(s.context.S.info.ver,undefined);});
test('healthy recognition checked every 10 seconds, keeps motion disabled; stale readback discarded',async()=>{const s=setup({lines:['OK INFO fw=PIANO_GLOVE_2 ver=2.2.4 armed=0']});await s.context.identifyOnce({},'COM3:1');assert.equal(s.context.S.needArm,true);s.advance(5000);await s.context.identifyOnce({},'COM3:1');assert.equal(s.stats().calls,1);s.advance(5000);await s.context.identifyOnce({},'COM3:1');assert.equal(s.stats().calls,2);let resolve;const t=setup(new Promise(r=>resolve=r));const run=t.context.identifyOnce({},'COM3:1');t.context.lastIdentity='COM4:2';resolve({lines:['OK INFO ver=2.2.4']});await run;assert.equal(t.context.S.info.ver,undefined);});
test('old backend failed-recognition flag does not permanently suppress retry; busy tasks avoid probes',async()=>{const s=setup({lines:['OK INFO ver=2.2.4']});await s.context.identifyOnce({firmwareRecognized:false},'COM3:1');assert.equal(s.stats().calls,1);s.advance(10000);s.context.active=()=>true;await s.context.identifyOnce({},'COM3:1');assert.equal(s.stats().calls,1);});
function reconnectSetup(){let calls=[],now=10000;const c={chosen:'COM4',switching:false,nextReconnectAt:0,reconnectFailures:0,Date:{now:()=>now},busy:()=>false,active:()=>false,paint(){},notice(){},window:{},syncIdentity:async s=>{assert.equal(s.connected,true);},api:async(p,b)=>{calls.push([p,b]);return p==='/api/status'?{connected:true,port:'COM4',connectedAt:20}:{ok:true,port:'COM4'};}};vm.createContext(c);vm.runInContext(reconnect,c);return {c,calls,advance:ms=>now+=ms};}
test('automatic reconnect prefers manual selected CP210x, otherwise first candidate; skips during motion or maintenance',async()=>{const s=reconnectSetup(),state={connected:false,ports:[{device:'COM3',candidate:true},{device:'COM4',eligible:true}]};await s.c.autoReconnect(state);assert.equal(s.calls[0][1].port,'COM4');assert.equal(s.calls[1][0],'/api/status');assert.equal(s.c.bridge.connected,true);s.calls.length=0;s.c.active=()=>true;await s.c.autoReconnect(state);assert.equal(s.calls.length,0);s.c.active=()=>false;s.c.busy=()=>true;await s.c.autoReconnect(state);assert.equal(s.calls.length,0);s.c.busy=()=>false;s.c.chosen='COM9';s.advance(3000);await s.c.autoReconnect(state);assert.equal(s.calls[0][1].port,'COM3');});
test('reconnect failures back off and unsupported ports are not opened',async()=>{const s=reconnectSetup();s.c.api=async()=>{s.calls.push(1);throw Error('port busy');};await s.c.autoReconnect({connected:false,ports:[{device:'COM3',candidate:true}]});await s.c.autoReconnect({connected:false,ports:[{device:'COM3',candidate:true}]});assert.equal(s.calls.length,1);s.advance(2000);await s.c.autoReconnect({connected:false,ports:[{device:'COM1',candidate:false}]});assert.equal(s.calls.length,1);await s.c.autoReconnect({connected:false,ports:[{device:'COM3',candidate:true}]});assert.equal(s.calls.length,2);assert.equal(s.c.nextReconnectAt,16000);});
test('fixed console never reconnects to another board when its USB is missing',async()=>{const s=reconnectSetup();await s.c.autoReconnect({connected:false,fixed:'COM27',ports:[{device:'COM3',candidate:true}]});assert.equal(s.calls.length,0);await s.c.autoReconnect({connected:false,fixed:'COM27',ports:[{device:'COM3',candidate:true},{device:'COM27',candidate:true}]});assert.equal(s.calls[0][1].port,'COM27');});
const paintSource=source.slice(source.indexOf('function paint('),source.indexOf('async function identifyOnce('));
test('closing flash progress keeps header progress clickable; verified state unlocks port selector',()=>{const nodes=new Map();const q=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='demoPort'?'COM3':'',classList:{toggle(){}}});return nodes.get(id);};const c={q,bridge:{connected:false,fixed:'COM3'},firmware:{busy:true,progress:40,phase:'write'},S:{info:{}},busy:()=>c.firmware.busy,active:()=>false,switching:false,attemptedIdentity:null,lastIdentity:'',notice(){},error:''};vm.createContext(c);vm.runInContext(paintSource,c);c.paint();assert.match(q('demoConnection').textContent,/40%/);assert.equal(q('demoConnection').disabled,false);assert.equal(q('demoPort').disabled,true);c.firmware={busy:false,verified:true,state:'verified'};c.bridge.connected=true;c.bridge.port='COM3';c.S.info={ver:'2.2.4',profile:'STS'};c.paint();assert.equal(q('demoPort').disabled,false);assert.equal(q('demoFlash').disabled,false);assert.match(q('demoConnection').textContent,/COM3/);});
test('paused bridge is not reclaimed by page auto reconnect',async()=>{const s=reconnectSetup();await s.c.autoReconnect({connected:false,paused:true,fixed:'COM4',ports:[{device:'COM4',candidate:true}]});assert.equal(s.calls.length,0);});
const connectSource=source.slice(source.indexOf('async function connect('),source.indexOf("q('demoConnection').onclick"));
test('selecting a peer device opens its console without repeated connect',async()=>{let destination;const c={busy:()=>false,active:()=>false,switching:false,error:'',paint(){},q:()=>({value:'COM27'}),api:async()=>({ok:true,redirect:'http://127.0.0.1:8124/web_piano_glove.html?simple=1'}),location:{assign:url=>destination=url},notice(){},refresh:()=>{throw Error('must navigate before refresh');}};vm.createContext(c);vm.runInContext(connectSource,c);await c.connect();assert.equal(destination,'http://127.0.0.1:8124/web_piano_glove.html?simple=1#play');assert.equal(c.switching,false);});
test('manual target survives polling while stopping active task',async()=>{let selected='COM3',sent;const c={busy:()=>false,active:()=>true,switching:false,error:'',paint(){},q:()=>({value:selected}),window:{deliveryDemoStop:async()=>{selected='COM27';}},api:async(p,b)=>{sent=b.port;return {ok:true};},notice(){},refresh:async()=>{}};vm.createContext(c);vm.runInContext(connectSource,c);await c.connect();assert.equal(sent,'COM3');});
