const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../web_piano_glove.html'),'utf8'),a=html.indexOf('function actionKV('),b=html.indexOf("const section=document.querySelector('#p-play');",a),Executor=vm.runInNewContext(html.slice(a,b)+'\nStrictActionExecutor',{setTimeout,clearTimeout});
const roles=['latch','press','press','press','press','press'];
test('partial-stroke speed uses separated endpoint windows and retains full-stroke35',async()=>{const f=setup({latency:5,benchFeedback:true});const r=await f.executor.runSpeedTest({amplitudes:[1,.5,.2],cycles:3},roles);assert.equal(r.results.length,3);for(const [i,tol]of [35,29,11].entries()){for(const leg of r.results[i].performance.legs){assert.equal(leg.arrivals.length,5);assert(leg.arrivals.every(a=>a.completionTolerance===tol&&a.error<=tol));}if(i)assert(tol*2<238*r.results[i].amplitude);}assert.equal(f.sent.at(-1),'SAFE');});
function setup({profile='SCS',benchFeedback=false,keep=false,travelMs=0,slow=false,escape=false,rateValid=true,noisy=false,stall=false,latency=0}={}){
 let clock=0,armed=false,benchActive=false,benchDeadline=0,rate=false,depth=0,polls=0;const sent=[],progress=[],pos=Array(6).fill(100),goals=Array(6).fill(100),origin=Array(6).fill(100),goalAt=Array(6).fill(0);
 const move=(i,target)=>{if(stall)return;origin[i]=pos[i];goalAt[i]=clock;goals[i]=target;};
 const io={safe:async()=>{sent.push('SAFE');armed=false;benchActive=false;},send:async c=>{sent.push(c);clock+=latency;
 if(travelMs)for(let i=0;i<6;i++)pos[i]=Math.round(origin[i]+(goals[i]-origin[i])*Math.min(1,(clock-goalAt[i])/travelMs));
 if(benchFeedback&&benchActive&&clock>=benchDeadline){armed=false;benchActive=false;}
 if(c==='INFO')return[`OK INFO fw=PIANO_GLOVE_2 ver=2.2.4 profile=${profile} range=${profile==='SCS'?1023:4095} calibrated=1 armed=${+armed} online=6 auto_active=0 enroll_active=0 sweep=0 bench_group=1 bench_feedback=${+benchFeedback} bench_keep=${+keep}`];
 if(c==='STATUS_ALL')return [...pos.map((p,s)=>`SLOT slot=${s} id=${s+1} min=100 max=${profile==='STS'?600:350} standby=100 pos=${p} online=1 valid=1 press=max`),'OK STATUS_ALL'];
 if(c==='ARM CHECK')return [...pos.map((p,s)=>`ARM_CHECK_SLOT slot=${s} id=${s+1} ok=1 torque=0 pos=${p} min=20 max=1003`),'OK ARM CHECK'];
 if(c==='ARM'){armed=true;return['OK ARM armed=1'];}
 if(c==='POSALL'){polls++;if(!travelMs)for(let i=0;i<6;i++)pos[i]=slow?pos[i]+Math.sign(goals[i]-pos[i])*Math.min(5,Math.abs(goals[i]-pos[i])):goals[i];if(noisy&&!armed)pos[2]=100+(polls%2)*20;return ['OK POSALL '+(escape?[999,...pos.slice(1)]:pos).join(' ')+(benchFeedback?` armed=${+armed} bench_active=${+benchActive}`:'')];}
 if(c==='BENCH KEEP'){if(!armed||!benchActive)return ['ERR BENCH KEEP inactive_or_expired'];benchDeadline=clock+1200;return ['OK BENCH KEEP active=1 armed=1 cutoff_ms=1200'];}
 if(c.startsWith('BENCH GROUP ')){const x=c.split(' '),mask=parseInt(x[2]);for(let id=1;id<=6;id++)if(mask&(1<<(id-1)))move(id-1,+x[id+2]);benchActive=true;benchDeadline=clock+1200;return [`OK BENCH GROUP mask=${x[2]} speed=${x[9]} readback=1 count=${Array.from({length:6},(_,i)=>!!(mask&(1<<i))).filter(Boolean).length} cutoff_ms=1200`+(benchFeedback?' armed=1 bench_active=1':'')];}
 if(c.startsWith('MOVE ')||c.startsWith('BENCH MOVE ')){const [,id,p]=(c.startsWith('BENCH ')?c.slice(6):c).split(' ');move(+id-1,+p);if(c.startsWith('BENCH ')){benchActive=true;benchDeadline=clock+1200;}return['OK MOVE'];}
 if(c.startsWith('RATE ')){rate=true;depth=+c.split(' ')[4];return['OK RATE_START'];}
 if(c==='RATE'){if(rate){rate=false;return[`OK RATE active=0 done=3/3 half_ms=50 full_ms=100 hz=${depth/10} lost=0 valid=${+rateValid}`];}return['OK RATE active=0 done=0/0'];}throw Error(c);}};
 return {io,sent,progress,executor:new Executor(io,{now:()=>clock,sleep:async m=>{clock+=m},progress:p=>progress.push(p)})};}

test('internal demo reaches every one of six slots including thumb lateral and then returns each to rest',async()=>{const f=setup();const events=Array.from({length:6},(_,slot)=>({slot,t_ms:slot*1000,duration_ms:300}));const result=await f.executor.run({events,duration_ms:6000},roles,{internalSlots:true});assert.equal(result.feedbackVerified,true);for(let id=1;id<=6;id++){assert(f.sent.includes(`MOVE ${id} 350 200 30`));assert(f.sent.includes(`MOVE ${id} 100 200 30`));}assert.equal(f.sent.at(-1),'SAFE');assert(f.progress.some(p=>p.targets?.some(t=>t.slot===1&&t.pos===350)));});
test('slow actual feedback travel exceeding former800msdeadline completes before releasing',async()=>{const f=setup({slow:true});await f.executor.run({events:[{slot:2,t_ms:0,duration_ms:300}],duration_ms:300},roles,{internalSlots:true});assert(f.progress.filter(p=>p.state==='press').at(-1).elapsed>800);const press=f.sent.indexOf('MOVE 3 350 200 30'),release=f.sent.indexOf('MOVE 3 100 200 30');assert(f.sent.slice(press,release).filter(x=>x==='POSALL').length>=43);});
test('feedback outside recorded sector aborts before movement',async()=>{const f=setup({escape:true});await assert.rejects(f.executor.run({events:[{slot:0,t_ms:0,duration_ms:300}],duration_ms:300},roles,{internalSlots:true}),/越出校准范围/);assert(!f.sent.some(c=>c.startsWith('MOVE')));assert.equal(f.sent.at(-1),'SAFE');});
test('legacy STS RATE cannot substitute for current five-finger synchronized test',async()=>{const f=setup({profile:'STS'});await assert.rejects(f.executor.runSpeedTest({slots:[1],amplitudes:[1]},roles),/更新/);assert(!f.sent.includes('ARM'));assert(!f.sent.some(c=>c.startsWith('RATE ')));assert.equal(f.sent.at(-1),'SAFE');});
test('legacy STS invalid RATE data never generates a frequency',async()=>{const f=setup({profile:'STS',rateValid:false});await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/更新/);assert.equal(f.sent.at(-1),'SAFE');});
test('all three PDF excerpts preserve source duration timeline and chord batches with100ms feedback travel',async()=>{const {songs,songPlan}=require('../delivery-demo.js');assert.equal(songs.length,3);for(const song of songs){const f=setup({travelMs:100,latency:5,benchFeedback:true}),events=songPlan(song).events;const result=await f.executor.run({...song,events},roles,{internalSlots:true});assert(result.feedbackVerified);assert(result.elapsed_ms<10000);assert(result.score_elapsed_ms>=song.duration_ms&&result.score_elapsed_ms<song.duration_ms+500);assert(!f.sent.some(c=>c.startsWith('MOVE ')||c.startsWith('BENCH MOVE ')));const expected=new Map();for(const event of events){if(!expected.has(event.t_ms))expected.set(event.t_ms,[]);expected.get(event.t_ms).push(event.slot+1);}const observed=[];for(const cmd of f.sent.filter(c=>c.startsWith('BENCH GROUP '))){const x=cmd.split(' '),mask=parseInt(x[2]),ids=[];for(let id=1;id<=6;id++)if((mask&(1<<(id-1)))&&+x[id+2]===344)ids.push(id);if(ids.length)observed.push(ids);}assert.deepEqual(observed,[...expected.values()].map(ids=>ids.sort((a,b)=>a-b)));assert.equal(f.sent.at(-1),'SAFE');}});

test('full user sequence completes six individual then 2 through6 combination and odd even alternation',async()=>{const {servoDemoPlan}=require('../delivery-demo.js'),f=setup(),p=servoDemoPlan();await f.executor.run(p,roles,{internalSlots:true});const done=f.progress.filter(x=>x.state==='press');assert.deepEqual(done.map(x=>Array.from(x.slots)),p.groups.map(g=>g.slots));assert(f.progress.at(-1).completed);});

test('passive idle slack inside recorded limits does not demand absolute immobility',async()=>{const f=setup({noisy:true});await f.executor.run({events:[{slot:0,t_ms:0,duration_ms:300}],duration_ms:300},roles,{internalSlots:true});assert(f.sent.includes('ARM'));assert(f.sent.includes('MOVE 1 350 200 30'));assert.equal(f.sent.at(-1),'SAFE');});

test('quick six separate groups use normal speed within budget and exclude preparationtime',async()=>{const f=setup({latency:10});const result=await f.executor.run({quickDemo:true,events:Array.from({length:6},(_,slot)=>({slot,t_ms:slot*100,duration_ms:60,amplitude:.35}))},roles,{internalSlots:true});assert(result.elapsed_ms<=4500);for(let id=1;id<=6;id++)assert(f.sent.includes(`MOVE ${id} 188 200 30`));assert.equal(f.sent.at(-1),'SAFE');});
test('quick budget stops unfinished motion and never claims completion',async()=>{const f=setup({latency:500});await assert.rejects(f.executor.run({quickDemo:true,events:Array.from({length:6},(_,slot)=>({slot,t_ms:slot*100,duration_ms:60,amplitude:.35}))},roles,{internalSlots:true}),/完整动作未在规定时间内完成/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});
test('full amplitude demo never accepts stalled servo as reached',async()=>{const f=setup({stall:true});await assert.rejects(f.executor.run({quickDemo:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:1}]},roles,{internalSlots:true}),/未到位/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});



test('hard watchdog sends SAFE while MOVE is pending and blocks restart until late command drains',async()=>{let watchdog,resolveMove,notify;const ready=new Promise(r=>notify=r),f=setup(),send=f.io.send;f.io.send=async cmd=>{if(cmd.startsWith('MOVE ')){notify();await new Promise(r=>resolveMove=r);}return send(cmd);};const Timed=vm.runInNewContext(html.slice(a,b)+'\nStrictActionExecutor',{setTimeout:cb=>{watchdog=cb;return 1;},clearTimeout:()=>{}}),ex=new Timed(f.io,{now:()=>0,sleep:async()=>{}}),plan={quickDemo:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:.35}]};const running=ex.run(plan,roles,{internalSlots:true});await ready;watchdog();await assert.rejects(running,/5秒展示未完成/);assert(f.sent.includes('SAFE'));await assert.rejects(ex.run(plan,roles,{internalSlots:true}),/正在停止/);resolveMove();await new Promise(r=>setImmediate(r));assert.equal(ex.pending,0);assert.equal(f.sent.at(-1),'SAFE');assert.equal(f.sent.filter(c=>c.startsWith('MOVE')).length,1);});

test('bench quick all six full amplitude uses1000 and only insets sixcounts within originalcalibration',async()=>{const f=setup();await f.executor.run({quickDemo:true,benchQuick:true,events:Array.from({length:6},(_,slot)=>({slot,t_ms:slot*100,duration_ms:60,amplitude:1}))},roles,{internalSlots:true});for(let id=1;id<=6;id++){assert(f.sent.includes(`BENCH MOVE ${id} 344 1000`));assert(f.sent.includes(`BENCH MOVE ${id} 106 1000`));}assert(!f.sent.some(c=>c.startsWith('MOVE ')));assert.equal(f.sent.at(-1),'SAFE');});
test('bench quick rejects reducedamplitude beforeARM',async()=>{const f=setup();await assert.rejects(f.executor.run({quickDemo:true,benchQuick:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:.35}]},roles,{internalSlots:true}),/100%/);assert(!f.sent.includes('ARM'));assert(!f.sent.some(c=>c.startsWith('BENCH')));});
test('bench quick rejects absent quickmode and unrelatedprofile',async()=>{const f=setup();await assert.rejects(f.executor.run({benchQuick:true,events:[{slot:0,t_ms:0,duration_ms:120,amplitude:1}]},roles,{internalSlots:true}),/已识别的短演示/);assert(!f.sent.includes('ARM'));});
test('transport deadline safety covers lateBENCH requests',()=>{assert.match(html,/\^\(ARM\|MOVE\|BENCH\)/);});
test('quick feedback reports measuredframes and frequency with serialized requests',async()=>{const f=setup({latency:5});const r=await f.executor.run({quickDemo:true,benchQuick:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:1}]},roles,{internalSlots:true});assert.equal(r.feedbackSamples,4);assert(r.feedbackHz>0);assert.equal(r.feedbackHz,Math.round(r.feedbackSamples*10000/r.elapsed_ms)/10);assert(f.progress.some(p=>p.feedbackSamples>0&&p.feedbackHz>0));});

test('SCS prepared start permits6count rebound but never7 orhardwarelimit escape',async()=>{for(const [position,hardwareLow,pass]of [[94,20,true],[93,20,false],[94,95,false]]){const f=setup(),base=f.io.send;f.io.send=async cmd=>{const lines=await base(cmd);if(cmd==='STATUS_ALL')return lines.map(l=>l.startsWith('SLOT slot=0 ')?l.replace('pos=100','pos='+position):l);if(cmd==='ARM CHECK')return lines.map(l=>l.startsWith('ARM_CHECK_SLOT slot=0 ')?l.replace('pos=100','pos='+position).replace('min=20','min='+hardwareLow):l);return lines;};if(pass){const ready=await f.executor.prepare(roles);assert.equal(ready.slots[0].press,350);assert.equal(ready.slots[0].rest,100);assert(!f.sent.some(c=>c.startsWith('MOVE')));}else await assert.rejects(f.executor.prepare(roles),/超出/);}});
test('SCS rebound allowance never bypasses failingARM CHECK',async()=>{const f=setup(),base=f.io.send;f.io.send=async cmd=>{const lines=await base(cmd);return cmd==='ARM CHECK'?lines.map(l=>l.startsWith('ARM_CHECK_SLOT slot=0 ')?l.replace('ok=1','ok=0').replace('pos=100','pos=94'):l):lines;};await assert.rejects(f.executor.prepare(roles),/准备状态未确认/);});

test('every arrival branch accepts35counts but rejects36',async()=>{for(const [quick,bench,scaledTolerance] of [[true,true,false],[false,false,false],[true,true,true]])for(const error of [35,36]){const f=setup({latency:20}),base=f.io.send;f.io.send=async cmd=>{const lines=await base(cmd);if(cmd==='POSALL'&&f.sent.some(c=>/^(BENCH MOVE|MOVE) /.test(c)))return ['OK POSALL '+[350-error,100,100,100,100,100].join(' ')];return lines;};const slots=Array.from({length:6},(_,i)=>({id:i+1,low:100,high:350,rest:100,press:350,tolerance:6}));await f.io.send('ARM');const run=f.executor.reach([{slot:0,amplitude:1}],slots,{profile:'SCS',range:1023},true,0,0,1,quick,bench,{scaledTolerance});if(error===35)await run;else await assert.rejects(run,/未到位/);}});
test('wearable full amplitude path keeps ordinaryspeed and permits longer feedback completion',async()=>{const f=setup({latency:70});const result=await f.executor.run({quickDemo:true,wearDemo:true,benchQuick:false,events:Array.from({length:6},(_,slot)=>({slot,t_ms:slot*700,duration_ms:60,amplitude:1}))},roles,{internalSlots:true});assert(result.feedbackVerified);assert(result.elapsed_ms<15000);assert(f.sent.includes('MOVE 1 350 200 30'));assert(!f.sent.some(c=>c.startsWith('BENCH')));assert.equal(f.sent.at(-1),'SAFE');});
for(const speed of [200,400,600,800,1000])test('validation full stroke six axes exact targets at '+speed,async()=>{const f=setup({latency:5});const result=await f.executor.runValidation({speed},roles);assert(result.feedbackVerified);assert.equal(result.protocol,'fullStroke-v1');assert(result.fullStroke);assert.equal(result.speed,speed);assert.equal(result.events,24);for(let id=1;id<=6;id++){const prefix=speed===200?'MOVE':'BENCH MOVE',tail=speed===200?' 30':'';assert.deepEqual(f.sent.filter(c=>c.startsWith(prefix+' '+id+' ')),[106,344,106,225].map(p=>`${prefix} ${id} ${p} ${speed}${tail}`));}assert.equal(f.sent.at(-1),'SAFE');assert(f.progress.some(p=>p.phase==='midpoint'));});
test('validation rejects nonstandard speed and forged score metadata before ARM',async()=>{for(const speed of [0,201,1200,'400']){const f=setup();await assert.rejects(f.executor.runValidation({speed},roles),/档位/);assert(!f.sent.includes('ARM'));}const f=setup();await assert.rejects(f.executor.run({validationOnly:true,validationSpeed:1000,fullStroke:true,quickDemo:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:1}]},roles,{internalSlots:true}),/专用流程/);assert(!f.sent.includes('ARM'));});
test('full stroke default demo uses only lift and press without intermediate midpoint',async()=>{const f=setup();const result=await f.executor.run({fullStroke:true,quickDemo:true,benchQuick:true,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:1}]},roles,{internalSlots:true});assert(result.fullStroke);assert.deepEqual(f.sent.filter(c=>c.startsWith('BENCH MOVE')),[106,344,106].map(p=>'BENCH MOVE 1 '+p+' 1000'));});
test('bench released after feedback does not falsely pass',async()=>{const f=setup(),base=f.io.send;let bench=false;f.io.send=async c=>{const lines=await base(c);if(c.startsWith('BENCH MOVE'))bench=true;if(bench&&c==='INFO')return lines.map(l=>l.replace('armed=1','armed=0'));return lines;};await assert.rejects(f.executor.runValidation({speed:400},roles),/已释放/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});
test('bench leg measured from before command stops before1200ms and no late arrival passes',async()=>{const f=setup(),base=f.io.send;f.io.send=async c=>{if(c.startsWith('BENCH MOVE'))await f.executor.sleep(1050);return base(c);};await assert.rejects(f.executor.runValidation({speed:400},roles),/未到位/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});
test('bench watchdog marker in response aborts the stage',async()=>{const f=setup(),base=f.io.send;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH MOVE')))lines.push('BENCH_DONE reason=deadline torque=off armed=0');return lines;};await assert.rejects(f.executor.runValidation({speed:600},roles),/已释放/);assert.equal(f.sent.at(-1),'SAFE');});
test('validation speed is not retained by later normal demo',async()=>{const f=setup();await f.executor.runValidation({speed:800},roles);f.sent.length=0;await f.executor.run({events:[{slot:0,t_ms:0,duration_ms:300,amplitude:1}]},roles,{internalSlots:true});assert(f.sent.includes('MOVE 1 350 200 30'));assert(!f.sent.some(x=>x.startsWith('BENCH MOVE')));});

test('min direction full stroke starts at opposite high endpoint and midpoint is only final standby',async()=>{const f=setup(),base=f.io.send;f.io.send=async c=>{const lines=await base(c);return c==='STATUS_ALL'?lines.map(l=>l.startsWith('SLOT ')?l.replace('press=max','press=min'):l):lines;};await f.executor.runValidation({speed:200},roles);for(let id=1;id<=6;id++)assert.deepEqual(f.sent.filter(c=>c.startsWith('MOVE '+id+' ')),[344,106,344,225].map(p=>`MOVE ${id} ${p} 200 30`));});
test('ordinary200 full stroke allows physicallylong travel without bench cutoff',async()=>{const f=setup({slow:true,latency:15});const r=await f.executor.runValidation({speed:200},roles);assert(r.completed);assert(r.elapsed_ms>1200);assert(!f.sent.some(c=>c.startsWith('BENCH')));assert.equal(f.sent.at(-1),'SAFE');});
test('slow armed confirmation after bench arrival cannot overrun leg deadline',async()=>{const f=setup(),base=f.io.send;let bench=false;f.io.send=async c=>{if(c.startsWith('BENCH MOVE'))bench=true;if(bench&&c==='INFO')await f.executor.sleep(1100);return base(c);};await assert.rejects(f.executor.runValidation({speed:400},roles),/超时/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});

test('SCS ensemble speed explicit fullstroke3cycles excludes preposition and final midpoint timing',async()=>{const f=setup({latency:5});const r=await f.executor.runSpeedTest({amplitudes:[1]},roles);assert.equal(r.results.length,1);const result=r.results[0];assert.equal(result.amplitude,1);assert.equal(result.cycles,3);assert(result.feedbackVerified);assert.equal(result.protocol,'scs-feedback-ensemble-v1');assert.equal(result.elapsed_ms,150);assert.equal(result.full_ms,50);assert.equal(result.hz,20);assert.equal(f.sent.filter(c=>c==='RATE').length,1);assert(!f.sent.some(c=>c.startsWith('RATE ')));assert.deepEqual(f.sent.filter(c=>c.startsWith('BENCH GROUP ')),[106,344,106,344,106,344,106,225].map((p,i)=>'BENCH GROUP '+(i===0||i===7?'0x3f':'0x3e')+' '+[225,...Array(5).fill(p)].join(' ')+' 1000'));assert(!f.sent.some(c=>c.startsWith('BENCH MOVE')));assert.equal(f.sent.at(-1),'SAFE');});
test('SCS explicit fractional amplitudes scale symmetrically around midpoint',async()=>{const f=setup({latency:5});const r=await f.executor.runSpeedTest({amplitudes:[.25,.5,1]},roles);assert.equal(r.results.length,3);for(const p of [255,285,344])assert(f.sent.includes('BENCH GROUP 0x3e '+[225,...Array(5).fill(p)].join(' ')+' 1000'));assert(!f.sent.some(c=>c.startsWith('RATE ')));});
test('SCS speed detects stalled ID and never reports a frequency',async()=>{const f=setup({latency:5,stall:true});await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/ID 1 未到位/);assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));});
test('SCS speed test still rejects incomplete return even with35count tolerance',async()=>{const f=setup({latency:5}),base=f.io.send;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.includes('BENCH GROUP 0x3e 225 255 255 255 255 255 1000'))return ['OK POSALL 225 235 255 255 255 255'];return lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[.25]},roles),/ID 2 未到位/);assert.equal(f.sent.at(-1),'SAFE');});
test('SCS speed rejects partial selection and tiny excursion before BENCH motion',async()=>{for(const options of [{slots:[1,2]},{amplitudes:[.001]}]){const f=setup({latency:5});await assert.rejects(f.executor.runSpeedTest(options,roles),/参数无效|过小|单指/);assert(!f.sent.some(c=>c.startsWith('BENCH ')));assert.equal(f.sent.at(-1),'SAFE');}});

test('combination writes one BENCH GROUP with ID indexed targets and accurate selected mask',async()=>{const f=setup({latency:5});await f.io.send('ARM');const slots=Array.from({length:6},(_,s)=>({id:s+1,low:100,high:350,rest:100,press:350,tolerance:6}));await f.executor.reach([{slot:1},{slot:4}],slots,{profile:'SCS',range:1023,bench_group:'1'},true,0,0,1,true,true);assert.deepEqual(f.sent.filter(c=>c.startsWith('BENCH ')),['BENCH GROUP 0x12 100 350 100 100 350 100 1000']);});
test('partial GROUP ack never passes a full ensemble leg',async()=>{const f=setup({latency:5}),base=f.io.send;f.io.send=async c=>{const lines=await base(c);return c.startsWith('BENCH GROUP')?lines.map(l=>l.replace('count=6','count=5')):lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/未完整确认/);assert.equal(f.sent.at(-1),'SAFE');});

test('SCS ensemble capability missing is explicit and never falls back to serial writes',async()=>{const f=setup({latency:5}),base=f.io.send;f.io.send=async c=>(await base(c)).map(l=>l.replace('bench_group=1','bench_group=0'));await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/同步控制/);assert(!f.sent.includes('ARM'));assert(!f.sent.some(c=>c.startsWith('BENCH')));assert.equal(f.sent.at(-1),'SAFE');});
test('SCS speed hard watchdog cancels pending GROUP and no late completion restarts motion',async()=>{let watchdog,resolveGroup,notify;const ready=new Promise(r=>notify=r),f=setup({latency:5}),send=f.io.send;f.io.send=async c=>{if(c.startsWith('BENCH GROUP ')){notify();await new Promise(r=>resolveGroup=r);}return send(c);};const Timed=vm.runInNewContext(html.slice(a,b)+'\nStrictActionExecutor',{setTimeout:cb=>{watchdog=cb;return 1;},clearTimeout:()=>{}}),ex=new Timed(f.io,{now:()=>0,sleep:async()=>{}});const running=ex.runSpeedTest({amplitudes:[1]},roles);await ready;watchdog();await assert.rejects(running,/测速超时/);await assert.rejects(ex.runSpeedTest({amplitudes:[1]},roles),/正在停止/);resolveGroup();await new Promise(r=>setImmediate(r));assert.equal(ex.pending,0);assert.equal(f.sent.filter(c=>c.startsWith('BENCH GROUP')).length,1);assert.equal(f.sent.at(-1),'SAFE');});

function rhythmPlan(events,duration=8160){return {rhythmDemo:true,quickDemo:true,fullStroke:true,benchQuick:true,duration_ms:duration,events};}
test('rhythm follows original340ms timestamps without adding per-note completion delays',async()=>{const f=setup({latency:5}),sentAt=[],base=f.io.send;f.io.send=async c=>{if(c.startsWith('BENCH GROUP'))sentAt.push({cmd:c,at:f.executor.now()});return base(c);};const events=Array.from({length:24},(_,i)=>({slot:[1,2,3,4,5][i%5],t_ms:i*340,duration_ms:280,amplitude:1}));const r=await f.executor.run(rhythmPlan(events),roles,{internalSlots:true});assert(r.completed);assert(r.feedbackVerified);assert.equal(r.protocol,'rhythm-fullStroke-v1');assert(r.elapsed_ms<10000);assert(r.score_elapsed_ms>=8160&&r.score_elapsed_ms<8260);const press=sentAt.filter(x=>x.cmd.split(' ').slice(3,9).includes('344'));assert.equal(press.length,24);for(let i=1;i<press.length;i++)assert(Math.abs(press[i].at-press[0].at-i*340)<=40);assert(sentAt.every(x=>x.cmd.split(' ')[3]==='106'));assert.equal(f.sent.at(-1),'SAFE');});
test('rhythm chord and mixed release/press at same timestamp use one simultaneous command',async()=>{const f=setup({latency:5});const events=[{slot:1,t_ms:0,duration_ms:340,amplitude:1},{slot:2,t_ms:0,duration_ms:340,amplitude:1},{slot:3,t_ms:340,duration_ms:280,amplitude:1}];const r=await f.executor.run(rhythmPlan(events,680),roles,{internalSlots:true});assert(r.completed);const groups=f.sent.filter(c=>c.startsWith('BENCH GROUP'));assert(groups.some(c=>c.startsWith('BENCH GROUP 0x6 106 344 344 ')));assert(groups.some(c=>c.startsWith('BENCH GROUP 0xe 106 106 106 344 ')));});
test('rhythm preserves1020ms original hold without premature watchdog assumptions',async()=>{const f=setup({latency:5});const r=await f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:1020,amplitude:1}],1360),roles,{internalSlots:true});assert(r.completed);assert(r.score_elapsed_ms>=1360);});
test('rhythm stalled finger aborts at scheduled release and never stretches time',async()=>{const f=setup({latency:5}),base=f.io.send;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP 0x2 ')))return ['OK POSALL 225 106 106 106 106 106'];return lines;};await assert.rejects(f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:280,amplitude:1}],680),roles,{internalSlots:true}),/ID 2 上一动作未到位/);assert.equal(f.sent.at(-1),'SAFE');});
test('rhythm delayed GROUP is not followed by catch-up notes',async()=>{const f=setup({latency:5}),base=f.io.send;f.io.send=async c=>{if(c.startsWith('BENCH GROUP 0x2 '))await f.executor.sleep(110);return base(c);};await assert.rejects(f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:280,amplitude:1},{slot:2,t_ms:340,duration_ms:280,amplitude:1}],680),roles,{internalSlots:true}),/延迟超过100/);assert(!f.sent.some(c=>c.startsWith('BENCH GROUP 0x4 ')));assert.equal(f.sent.at(-1),'SAFE');});

test('ensemble speed performance reports command vs preflight vs feedback time without peak claim',async()=>{const f=setup({latency:5});const r=await f.executor.runSpeedTest({amplitudes:[1]},roles),m=r.results[0].performance;assert.equal(m.legs.length,6);assert.equal(m.commandMs,30);assert.equal(m.preflightMs,60);assert.equal(m.feedbackWaitMs,60);assert.equal(m.INFO_calls,12);assert.equal(m.POSALL_calls,12);assert.equal(m.commandMs+m.preflightMs+m.feedbackWaitMs,r.results[0].elapsed_ms);});

test('modern feedback capability skips per-leg INFO and reuses recent reached frames',async()=>{const f=setup({latency:5,benchFeedback:true});const r=await f.executor.runSpeedTest({amplitudes:[1]},roles),m=r.results[0].performance;assert.equal(m.INFO_calls,0);assert.equal(m.preflightMs,0);assert.equal(m.commandMs,30);assert.equal(m.feedbackWaitMs,30);assert.equal(m.POSALL_calls,6);assert.equal(r.results[0].elapsed_ms,60);assert.equal(f.sent.filter(c=>c==='INFO').length,2);});
test('modern POSALL expiry prevents target-near-feedback from passing',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP')))return lines.map(l=>l.replace('armed=1 bench_active=1','armed=0 bench_active=0'));return lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/已释放/);assert.equal(f.sent.at(-1),'SAFE');});
test('modern GROUP ack must confirm active state',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;f.io.send=async c=>(await base(c)).map(l=>c.startsWith('BENCH GROUP')?l.replace('bench_active=1','bench_active=0'):l);await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/控制状态未确认/);assert.equal(f.sent.at(-1),'SAFE');});
test('rhythm elapsed includes prepare and ARM overhead; slow prepare consumes10s budget',async()=>{const f=setup({latency:5,benchFeedback:true});const result=await f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:280,amplitude:1}],680),roles,{internalSlots:true});assert(result.elapsed_ms>=result.score_elapsed_ms+45);const slow=setup({latency:1500,benchFeedback:true});await assert.rejects(slow.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:280,amplitude:1}],8160),roles,{internalSlots:true}),/规定时间/);assert.equal(slow.sent.at(-1),'SAFE');});

test('rhythm rejects thumb lateral slot instead of treating it as a musical finger',async()=>{const f=setup({latency:5,benchFeedback:true});await assert.rejects(f.executor.run(rhythmPlan([{slot:0,t_ms:0,duration_ms:280,amplitude:1}],680),roles,{internalSlots:true}),/侧摆保持休止/);assert(!f.sent.some(c=>c.startsWith('BENCH')));assert.equal(f.sent.at(-1),'SAFE');});

test('actual per ID first35count arrival records observed frame once without synthesizing timings',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let frame=0;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){frame++;const positions=frame===1?[320,200,200,200,200,200]:frame===2?[321,320,200,200,200,200]:Array(6).fill(344);return ['OK POSALL '+positions.join(' ')+' armed=1 bench_active=1'];}return lines;};await f.io.send('ARM');const slots=Array.from({length:6},(_,s)=>({id:s+1,low:100,high:350,rest:100,press:344,tolerance:6}));const leg=await f.executor.reach(slots.map((_,slot)=>({slot})),slots,{profile:'SCS',range:1023,bench_group:'1',bench_feedback:'1'},true,0,0,1,true,true);assert.deepEqual(Array.from(leg.arrivals,v=>[v.id,v.target,v.current,v.error,v.elapsed_ms]),[[1,344,320,24,10],[2,344,320,24,16],[3,344,344,0,22],[4,344,344,0,22],[5,344,344,0,22],[6,344,344,0,22]]);});
test('one incomplete feedback frame retries once using full fresh response and counts retry',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let failed=false;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&!failed&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){failed=true;return ['OK POSALL 106 106 106 106 106 -1 armed=1 bench_active=1'];}return lines;};const r=await f.executor.runSpeedTest({amplitudes:[1]},roles);assert(r.completed);assert.equal(r.results[0].feedbackRetries,1);assert.equal(f.executor.feedbackStats().feedbackRetries,1);assert.equal(f.sent.at(-1),'SAFE');});
test('persistent missing feedback retries only once then stops',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let invalidReads=0;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){invalidReads++;return ['OK POSALL 106 106 106 106 106 -1 armed=1 bench_active=1'];}return lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/反馈丢失/);assert.equal(invalidReads,2);assert.equal(f.executor.feedbackStats().feedbackRetries,1);assert.equal(f.sent.at(-1),'SAFE');});
test('released incomplete feedback stops immediately without retry',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let invalidReads=0;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){invalidReads++;return ['OK POSALL 106 106 106 106 106 -1 armed=0 bench_active=0'];}return lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/已释放/);assert.equal(invalidReads,1);assert.equal(f.executor.feedbackStats().feedbackRetries,0);assert.equal(f.sent.at(-1),'SAFE');});
test('feedback retry respects existing deadline and cannot reset cutoff',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let invalid=false;f.io.send=async c=>{if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){if(!invalid){invalid=true;return ['OK POSALL 106 106 106 106 106 -1 armed=1 bench_active=1'];}await f.executor.sleep(45000);}return base(c);};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/规定时间/);assert.equal(f.executor.feedbackStats().feedbackRetries,1);assert.equal(f.sent.at(-1),'SAFE');});

test('retry completing after per-leg cutoff cannot pass near target',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let bad=false;f.io.send=async c=>{if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){if(!bad){bad=true;return ['OK POSALL 106 106 106 106 106 -1 armed=1 bench_active=1'];}await f.executor.sleep(1050);}return base(c);};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/未到位/);assert.equal(f.executor.feedbackStats().feedbackRetries,1);assert.equal(f.sent.at(-1),'SAFE');});
test('rhythm tail rest beyond watchdog returns midpoint and SAFE before waiting',async()=>{const f=setup({latency:5,travelMs:260,benchFeedback:true});const r=await f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:400,amplitude:1}],2400),roles,{internalSlots:true});assert(r.completed);assert(r.score_elapsed_ms>=2400);const firstSafe=f.sent.indexOf('SAFE'),lastGroup=f.sent.map((c,i)=>c.startsWith('BENCH GROUP')?i:-1).filter(i=>i>=0).at(-1);assert(firstSafe>lastGroup);assert(!f.sent.slice(firstSafe+1).some(c=>c==='POSALL'||c==='INFO'||c.startsWith('BENCH')));assert(f.progress.some(p=>p.tailRest));assert.equal(f.sent.at(-1),'SAFE');});

test('release on second fresh frame stops instead of borrowing prior complete values',async()=>{const f=setup({latency:5,benchFeedback:true}),base=f.io.send;let invalid=false;f.io.send=async c=>{const lines=await base(c);if(c==='POSALL'&&f.sent.some(x=>x.startsWith('BENCH GROUP'))){if(!invalid){invalid=true;return ['OK POSALL 106 106 106 106 106 -1 armed=1 bench_active=1'];}return ['OK POSALL 106 106 106 106 106 106 armed=0 bench_active=0'];}return lines;};await assert.rejects(f.executor.runSpeedTest({amplitudes:[1]},roles),/已释放/);assert.equal(f.executor.feedbackStats().feedbackRetries,1);assert.equal(f.sent.at(-1),'SAFE');});

function stsSetup({travelMs=0,stall=false,missingKeep=false,released=false}={}){
 const f=setup({profile:'STS',benchFeedback:true,travelMs,stall,latency:5}),base=f.io.send;
 f.io.send=async cmd=>{if(cmd==='BENCH KEEP'){f.sent.push(cmd);if(released)return ['OK BENCH KEEP active=0 armed=0'];await base('BENCH GROUP 0x0 100 100 100 100 100 100 200');return ['OK BENCH KEEP active=1 armed=1 cutoff_ms=1200'];}const lines=await base(cmd);if(cmd==='INFO')return lines.map(l=>l+' bench_sts=1 bench_fullstroke=1 motion_speed_unit=counts_per_s bench_speed_max=8000 bench_default_speed=1000 bench_keep='+Number(!missingKeep));if(cmd.startsWith('BENCH GROUP '))return lines.map(l=>l+' actual_speed='+cmd.split(' ').at(-1));if(cmd.startsWith('BENCH MOVE '))return ['OK BENCH MOVE actual_speed='+cmd.split(' ').at(-1)+' readback=1 armed=1 bench_active=1'];return lines;};return f;
}
test('STS full-stroke validation uses normalized BENCH200 with4095 profile and90percent travel',async()=>{const f=stsSetup();const r=await f.executor.runValidation({speed:200},roles);assert(r.completed);assert(f.sent.includes('BENCH MOVE 1 575 200'));assert(f.sent.includes('BENCH MOVE 1 125 200'));assert(!f.sent.some(s=>s.startsWith('MOVE ')));assert.equal(f.sent.at(-1),'SAFE');});
test('STS six synchronized full-stroke speed accepts8000 and reports family unit without maximum claim',async()=>{const f=stsSetup();const r=await f.executor.runSpeedTest({speed:8000,amplitudes:[1],cycles:3},roles);assert.equal(r.results[0].speed,8000);assert.equal(r.results[0].family,'STS');assert.equal(r.results[0].speedUnit,'counts_per_s');assert(f.sent.some(s=>s.startsWith('BENCH GROUP 0x3f ')&&s.endsWith(' 8000')));assert(!f.sent.some(s=>s.startsWith('BENCH MOVE')));assert(r.results[0].performance.legs.every(l=>l.arrivals.every(a=>a.completionTolerance===114)));assert.equal(f.sent.at(-1),'SAFE');});
test('STS slow feedback leg renews watchdog without changing target or arrival deadline',async()=>{const f=stsSetup({travelMs:1800});const r=await f.executor.runValidation({speed:200},roles);assert(r.completed);assert(f.sent.includes('BENCH KEEP'));assert.equal(f.sent.at(-1),'SAFE');});
test('STS persistent stalled feedback still fails original deadline despite KEEP',async()=>{const f=stsSetup({stall:true});await assert.rejects(f.executor.runValidation({speed:200},roles),/未到位/);assert(f.sent.includes('BENCH KEEP'));assert.equal(f.sent.at(-1),'SAFE');});
test('STS requires KEEP capability before ARM and cannot resurrect released watchdog',async()=>{let f=stsSetup({missingKeep:true});await assert.rejects(f.executor.runValidation({speed:200},roles),/更新/);assert(!f.sent.includes('ARM'));f=stsSetup({travelMs:1800,released:true});await assert.rejects(f.executor.runValidation({speed:200},roles),/保持未确认/);assert.equal(f.sent.at(-1),'SAFE');});


test('trusted STS demo speed8000 reaches4095-range mixed-direction targets and score cannot override it',async()=>{const f=stsSetup(),base=f.io.send;f.io.send=async cmd=>{const lines=await base(cmd);if(cmd==='STATUS_ALL')return lines.map(l=>l.startsWith('SLOT ')?l.replace('max=600','max=3600').replace('press=max','press=min'):l);if(cmd==='ARM CHECK')return lines.map(l=>l.replace('max=1003','max=4095'));return lines;};const result=await f.executor.run({quickDemo:true,benchQuick:true,fullStroke:true,runtimeSpeed:99,events:[{slot:0,t_ms:0,duration_ms:60,amplitude:1}]},roles,{internalSlots:true,demoSpeed:8000});assert(result.completed);assert(f.sent.includes('BENCH MOVE 1 3425 8000'));assert(f.sent.includes('BENCH MOVE 1 275 8000'));assert(!f.sent.includes('BENCH MOVE 1 1850 8000'));assert(!f.sent.some(c=>c.endsWith(' 99')));});
test('SCS cannot accept STS speed8000 before ARM',async()=>{const f=setup();await assert.rejects(f.executor.runValidation({speed:8000},roles),/档位/);assert(!f.sent.includes('ARM'));});

test('due rhythm batch prioritizes fresh complete feedback over another costly poll',async()=>{const f=setup({benchFeedback:true,latency:5}),base=f.io.send,sleep=f.executor.sleep;let scoreAt=null,jumped=false,next=[];f.io.send=async cmd=>{if(cmd.startsWith('BENCH GROUP 0x2 '))scoreAt??=f.executor.now();if(jumped)next.push(cmd);if(jumped&&cmd==='POSALL')await sleep(80);return base(cmd);};f.executor.sleep=async ms=>{await sleep(ms);if(!jumped&&scoreAt!==null&&f.executor.now()-scoreAt>=370&&f.executor.now()-scoreAt<400){await sleep(55);jumped=true;}};const r=await f.executor.run(rhythmPlan([{slot:1,t_ms:0,duration_ms:400,amplitude:1},{slot:2,t_ms:400,duration_ms:400,amplitude:1}],1200),roles,{internalSlots:true});assert(r.completed);assert(jumped);assert(next[0].startsWith('BENCH GROUP 0x6 '));assert.equal(f.sent.at(-1),'SAFE');});

test('STS speed full setting commands only centered90percent while calibration remains intact',async()=>{const f=stsSetup();await f.executor.runSpeedTest({speed:8000,amplitudes:[1,.5,.2],cycles:3},roles);const packets=f.sent.filter(s=>s.startsWith('BENCH GROUP ')).map(s=>s.split(' ').slice(3,9).map(Number));assert(packets.some(p=>p[0]===350&&p.slice(1).every(v=>v===125)));assert(packets.some(p=>p[0]===350&&p.slice(1).every(v=>v===575)));assert(packets.every(p=>p.every(v=>v>=125&&v<=575)));assert(!f.sent.some(c=>/^CAL |^SETDIR /.test(c)));});

test('new physical mapping keeps ID1 midpoint while ID2 thumb press follows either recorded direction',async()=>{for(const direction of ['min','max']){const f=setup({benchFeedback:true,latency:5}),base=f.io.send;f.io.send=async c=>(await base(c)).map(l=>c==='STATUS_ALL'&&l.startsWith('SLOT slot=1 ')?l.replace('press=max','press='+direction):l);const plan=require('../delivery-demo.js').servoDemoPlan('single');const result=await f.executor.run(plan,roles,{internalSlots:true});assert(result.completed);const id1=f.sent.filter(c=>c.startsWith('BENCH MOVE 1 '));assert(id1.length>0);assert(id1.every(c=>c==='BENCH MOVE 1 225 1000'));assert(f.sent.includes('BENCH MOVE 2 344 1000'));assert(f.sent.includes('BENCH MOVE 2 106 1000'));assert(!plan.events.some(e=>e.slot===0));}});
test('thumb-only and five-finger STS speed hold ID1 midpoint and report accurate active axes',async()=>{for(const selected of [[1],[1,2,3,4,5]]){const f=stsSetup();const result=await f.executor.runSpeedTest({slots:selected,speed:8000,amplitudes:[1],cycles:3},roles);assert.deepEqual(Array.from(result.results[0].slots),selected);assert.deepEqual(Array.from(result.results[0].heldSlots),[0]);for(const c of f.sent.filter(c=>c.startsWith('BENCH GROUP ')))assert.equal(Number(c.split(' ')[3]),350);assert(!f.sent.some(c=>c.startsWith('BENCH MOVE 1 ')));assert(f.sent.some(c=>selected.length===1?c.startsWith('BENCH MOVE 2 '):c.startsWith('BENCH GROUP 0x3e ')));assert.equal(f.sent.at(-1),'SAFE');}});
test('old role configuration migrates to ID1 side-axis ID2 thumb-press default',()=>{const i=html.indexOf('const ROLE_DEFAULT ='),j=html.indexOf('const ROLES =',i),normalize=vm.runInNewContext(html.slice(i,j)+'normalizeGloveRoles');assert.deepEqual(Array.from(normalize(['press','latch','press','press','press','press'])),roles);assert.deepEqual(Array.from(normalize(roles)),roles);});

test('song fingering maps 1 through5 to actual IDs2 through6 and reports acknowledged presses',async()=>{const {songPlan}=require('../delivery-demo.js'),f=setup({latency:5,benchFeedback:true});const plan=songPlan(rhythmPlan(Array.from({length:5},(_,i)=>({finger:i+1,t_ms:i*400,duration_ms:280,amplitude:1})),2200));await f.executor.run(plan,roles,{internalSlots:true});const observed=f.progress.filter(p=>p.rhythm&&p.slots&&p.on);assert.deepEqual(observed.map(p=>Array.from(p.slots)),[[1],[2],[3],[4],[5]]);assert.deepEqual(observed.map(p=>Array.from(p.pressedSlots)),[[1],[2],[3],[4],[5]]);for(const cmd of f.sent.filter(c=>c.startsWith('BENCH GROUP ')))assert.equal(cmd.split(' ')[3],'106');});

test('imported score parser uses the same five physical IDs as built-in songs',()=>{const start=html.indexOf('const FINGER_TO_SLOT'),end=html.indexOf('function actionKV(',start);const parse=vm.runInNewContext(html.slice(start,end)+'\nparseActionFile');const r=parse({version:1,name:'mapping',events:Array.from({length:5},(_,i)=>({finger:i+1,t_ms:i*500,duration_ms:200}))});assert.deepEqual(Array.from(r.events,e=>e.slot+1),[2,3,4,5,6]);});

test('all three songs keep unused fingers lifted and never command a playing finger to midpoint',async()=>{const {songs,songPlan}=require('../delivery-demo.js');for(const song of songs){const f=setup({latency:5,benchFeedback:true});await f.executor.run(songPlan(song),roles,{internalSlots:true});const commands=f.sent.filter(c=>c.startsWith('BENCH GROUP '));for(const cmd of commands){const x=cmd.split(' '),mask=parseInt(x[2]);if(mask&1)assert.equal(+x[3],106);for(let id=2;id<=6;id++)if(mask&(1<<(id-1)))assert([106,344].includes(+x[id+2]),cmd);}for(const cmd of [commands[0],commands.at(-1)])assert.deepEqual(cmd.split(' ').slice(3,9).map(Number),[106,106,106,106,106,106]);assert.equal(f.sent.at(-1),'SAFE');}});

test('song ID1 holds lifted endpoint in either calibrated direction instead of midpoint',async()=>{const {songPlan}=require('../delivery-demo.js');for(const direction of ['min','max']){const f=stsSetup(),base=f.io.send;f.io.send=async cmd=>{const lines=await base(cmd);return cmd==='STATUS_ALL'?lines.map(l=>l.startsWith('SLOT slot=0 ')?l.replace('press=max','press='+direction):l):lines;};await f.executor.run(songPlan(rhythmPlan([{finger:1,t_ms:0,duration_ms:300,amplitude:1}],650)),roles,{internalSlots:true});const targets=f.sent.filter(c=>c.startsWith('BENCH GROUP ')&&(parseInt(c.split(' ')[2])&1)).map(c=>+c.split(' ')[3]);assert.equal(targets.length,1);assert(targets.every(p=>p===(direction==='min'?575:125)));assert.equal(f.sent.at(-1),'SAFE');}});

// A long SC09 movement must retain the firmware watchdog, not fail at the
// former unconditional one-second host deadline. It must still time out on stall.
test('SC09 slow-stage travel uses acknowledged KEEP and bounded travel deadline',async()=>{
 const f=setup({travelMs:1400,latency:10,benchFeedback:true,keep:true});
 const r=await f.executor.runSpeedTest({slots:[1,2,3,4,5],amplitudes:[1],cycles:3,speed:400},roles);
 assert(r.completed);assert(f.sent.includes('BENCH KEEP'));assert.equal(f.sent.at(-1),'SAFE');
 assert(r.results[0].elapsed_ms>2000);assert(r.results[0].performance.KEEP_calls>0);
});
test('SC09 KEEP never turns a stalled axis into completion or an unbounded hold',async()=>{
 const f=setup({stall:true,latency:10,benchFeedback:true,keep:true});
 await assert.rejects(f.executor.runSpeedTest({cycles:3,speed:400},roles),/未到位/);
 assert(f.sent.includes('BENCH KEEP'));assert.equal(f.sent.at(-1),'SAFE');assert(!f.progress.some(p=>p.completed));
});

test('SC09 model-specific songs finish with 300ms feedback travel and keep chord batches',async()=>{
 const {songs,songForProfile,songPlan}=require('../delivery-demo.js');
 for(const source of songs){const f=setup({travelMs:300,latency:5,benchFeedback:true,keep:true});
 const song=songPlan(songForProfile(source,'SCS'));const r=await f.executor.run(song,roles,{internalSlots:true});
 assert(r.feedbackVerified);assert(r.elapsed_ms<10000);assert(r.score_elapsed_ms>=6400);
 assert(!f.sent.some(c=>c.startsWith('BENCH MOVE ')||c.startsWith('MOVE ')));
 assert(f.sent.filter(c=>c.startsWith('BENCH GROUP ')).every(c=>c.endsWith(' 1000')));
 assert.equal(f.sent.at(-1),'SAFE');}
});


test('STS passive rebound allows114 counts but never115 or hardware-limit escape; targets remain calibrated',async()=>{
 for(const [position,hardwareLow,hardwareHigh,pass]of [[76,20,1003,true],[714,20,1003,true],[715,20,1003,false],[76,77,1003,false],[714,20,713,false]]){
  const f=stsSetup(),base=f.io.send;
  f.io.send=async cmd=>{const lines=await base(cmd);if(cmd==='STATUS_ALL')return lines.map(l=>l.startsWith('SLOT slot=0 ')?l.replace('pos=100','pos='+position):l);if(cmd==='ARM CHECK')return lines.map(l=>l.startsWith('ARM_CHECK_SLOT slot=0 ')?l.replace('pos=100','pos='+position).replace('min=20','min='+hardwareLow).replace('max=1003','max='+hardwareHigh):l);if(cmd==='POSALL')return lines.map(l=>l.replace('OK POSALL 100 ','OK POSALL '+position+' '));return lines;};
  if(pass){const {slots}=await f.executor.prepare(roles);assert.equal(slots[0].low,100);assert.equal(slots[0].high,600);assert.equal(slots[0].press,600);assert.equal(slots[0].tolerance,114);assert(!f.sent.some(c=>c.startsWith('BENCH')||c.startsWith('MOVE')));}
  else await assert.rejects(f.executor.prepare(roles),/超出/);
 }
});
test('prepared STS live feedback enforces114-count calibration slack and strict hardware bounds',async()=>{
 for(const [position,hardwareHigh,pattern]of [[714,1003,null],[715,1003,/校准范围/],[714,713,/硬件范围/]]){
 const f=stsSetup(),{slots}=await f.executor.prepare(roles),base=f.io.send;slots[0].hardwareHigh=hardwareHigh;
 f.io.send=async cmd=>cmd==='POSALL'?['OK POSALL '+[position,100,100,100,100,100].join(' ')+' armed=0 bench_active=0']:base(cmd);
 if(pattern)await assert.rejects(f.executor.positions(slots,4095),pattern);else assert.equal((await f.executor.positions(slots,4095))[0],714);
 }
});

test('default speed sweep and UI use20 through100 percent ascending with per-stage per-finger timings',async()=>{
 for(const f of [setup({latency:5,benchFeedback:true}),stsSetup()]){
  const r=await f.executor.runSpeedTest({},roles);
  assert.deepEqual(Array.from(r.results,x=>x.amplitude),[.2,.4,.6,.8,1]);
  for(const stage of r.results){assert(stage.feedbackVerified);assert.equal(stage.cycles,3);assert.equal(stage.performance.legs.length,6);assert(stage.performance.legs.every(leg=>leg.arrivals.length===5));}
 }
 const ui=fs.readFileSync(path.join(__dirname,'../delivery-demo.js'),'utf8');assert.match(ui,/amplitudes:\[\.2,\.4,\.6,\.8,1\],cycles:3/);assert.match(fs.readFileSync(path.join(__dirname,'../delivery-speed-chart.js'),'utf8'),/查看各手指速度/);
});

for(const [family,heldTolerance,measurementTolerance]of [['SCS',35,6],['STS',114,24]]){
 test(family+' held ID1 uses action tolerance while measured fingers retain strict measurement tolerance',async()=>{
  for(const [heldError,measuredError,pass]of [[heldTolerance,measurementTolerance,true],[heldTolerance+1,0,false],[0,measurementTolerance+1,false]]){
   const f=family==='STS'?stsSetup():setup({latency:5,benchFeedback:true}),base=f.io.send;
   const slots=Array.from({length:6},(_,i)=>({id:i+1,low:100,high:600,rest:100,press:500,lift:100,midpoint:350,holdMidpoint:i===0,tolerance:family==='STS'?114:6,measurementTolerance}));
   f.io.send=async cmd=>{const lines=await base(cmd);return cmd==='POSALL'&&f.sent.some(c=>c.startsWith('BENCH GROUP '))?['OK POSALL '+[350+heldError,100+measuredError,100,100,100,100].join(' ')+' armed=1 bench_active=1']:lines;};
   await f.io.send('ARM');
   const info={profile:family,range:family==='STS'?4095:1023,bench_group:'1',bench_feedback:'1',bench_sts:'1',bench_fullstroke:'1',bench_keep:'1',motion_speed_unit:'counts_per_s'};
   const run=f.executor.reach([{slot:0},{slot:1}],slots,info,false,0,0,1,true,true,{scaledTolerance:true,phase:'lift'});
   if(pass){const leg=await run;assert.equal(leg.arrivals.find(a=>a.id===1).completionTolerance,heldTolerance);assert.equal(leg.arrivals.find(a=>a.id===2).completionTolerance,measurementTolerance);}else await assert.rejects(run,/未到位/);
  }
 });
}

for(const family of ['SCS','STS'])test(family+' five amplitude stages are centered, preserve direction and full endpoints',async()=>{
 for(const direction of ['min','max']){const f=family==='STS'?stsSetup():setup({latency:5,benchFeedback:true}),send=f.io.send;
 f.io.send=async cmd=>(await send(cmd)).map(l=>cmd==='STATUS_ALL'&&l.startsWith('SLOT ')?l.replace('press=max','press='+direction):l);
 const r=await f.executor.runSpeedTest({},roles),lo=family==='STS'?125:106,hi=family==='STS'?575:344,center=(lo+hi)/2;
 for(const stage of r.results){const expected=[Math.round(center+(lo-center)*stage.amplitude),Math.round(center+(hi-center)*stage.amplitude)];for(const leg of stage.performance.legs){assert(leg.arrivals.every(a=>expected.includes(a.target)));assert(leg.arrivals.every(a=>a.id!==1));}assert.equal(stage.performance.legs[0].arrivals[0].target,expected[direction==='min'?0:1]);assert.equal(stage.performance.legs[1].arrivals[0].target,expected[direction==='min'?1:0]);}
 }
});
for(const family of ['SCS','STS'])test(family+' centered speed does not reinterpret unsupported wrapped calibration as a long linear path',async()=>{
 const f=family==='STS'?stsSetup():setup({latency:5,benchFeedback:true}),send=f.io.send;
 f.io.send=async cmd=>(await send(cmd)).map(l=>cmd==='STATUS_ALL'&&l.startsWith('SLOT ')?l.replace(/min=100 max=\d+/,'min='+(family==='STS'?3900:950)+' max=50'):l);
 await assert.rejects(f.executor.runSpeedTest({},roles),/跨零/);assert(!f.sent.includes('ARM'));assert(!f.sent.some(c=>c.startsWith('BENCH')));
});
