const test=require('node:test'),assert=require('node:assert/strict');const {controller}=require('../delivery-mount.js');
function fixture({partial=false,startPending=false}={}){let connected=true,identity='COM3:1',timer,invalid=0,complete=0,resolveStart;const sent=[];const h={getState:()=>({connected,identity}),invalidateCalibration:()=>invalid++,onComplete:()=>complete++,send:async cmd=>{sent.push(cmd);if(cmd==='MOUNT START'){if(startPending)await new Promise(r=>resolveStart=r);return['OK MOUNT START active=1 target=512 speed=200 watchdog_ms=3000'];}if(cmd==='MOUNT STOP')return['OK MOUNT STOP active=0 torque=off verified=1'];if(cmd==='MOUNT KEEP')return['OK MOUNT KEEP active=1 watchdog_ms=3000'];return [...Array.from({length:partial?5:6},(_,i)=>`MOUNT_SLOT id=${i+1} pos=512 ready=1`),'OK MOUNT STATUS active=1 target=512 ready_mask=0x3F ready=1 reason=none'];}};const c=controller(h,{setTimer:cb=>(timer=cb,1),clearTimer:()=>{timer=null}});return {h,c,sent,get invalid(){return invalid},get complete(){return complete},fire:async()=>{timer?.();await new Promise(r=>setImmediate(r));},disconnect:()=>connected=false,reconnect:()=>identity='COM3:2',resolveStart:()=>resolveStart()};}
test('mount confirmation gate sends nothing before armsremoved checkbox',async()=>{const f=fixture();await assert.rejects(f.c.start(false),/拆下六个/);assert.deepEqual(f.sent,[]);});
test('six true feedback rows unlock finish, clear oldcal after ack and release before completion',async()=>{const f=fixture();await f.c.start(true);assert.equal(f.invalid,1);assert.equal(f.c.state().ready,true);await f.c.finish();assert.equal(f.complete,1);assert.equal(f.sent.at(-1),'MOUNT STOP');assert.equal(f.c.state().busy,false);});
test('summary ready flag without six realrows cannot finish',async()=>{const f=fixture({partial:true});await f.c.start(true);assert.equal(f.c.state().ready,false);await assert.rejects(f.c.finish(),/尚未到位/);assert.equal(f.complete,0);await f.c.stop();});
test('keep is serialized and reconnect releases without automaticrestart',async()=>{const f=fixture();await f.c.start(true);f.reconnect();await f.fire();assert.equal(f.c.state().busy,false);assert.match(f.c.state().message,/重连/);assert.equal(f.sent.filter(c=>c==='MOUNT START').length,1);assert.equal(f.sent.at(-1),'MOUNT STOP');});
test('stop during lateSTART waits and releases again, never resumes keep',async()=>{const f=fixture({startPending:true}),start=f.c.start(true);await new Promise(r=>setImmediate(r));const stop=f.c.stop();f.resolveStart();await Promise.all([start,stop]);assert.equal(f.c.state().busy,false);assert.equal(f.sent.at(-1),'MOUNT STOP');assert(!f.sent.includes('MOUNT KEEP'));assert.equal(f.invalid,0);});
test('disconnect stops mount flow and never resumes on its own',async()=>{const f=fixture();await f.c.start(true);f.disconnect();await f.fire();assert.equal(f.c.state().busy,false);assert.match(f.c.state().message,/连接已断开/);assert.equal(f.sent.filter(c=>c==='MOUNT START').length,1);});

test('multiline start and status use180msquiet',async()=>{const f=fixture(),base=f.h.send,requests=[];f.h.send=async(...args)=>{requests.push(args);return base(...args);};await f.c.start(true);assert(requests.filter(a=>a[0]==='MOUNT START'||a[0]==='MOUNT STATUS').every(a=>a[2]===180));await f.c.stop();});
test('STOP failure falls back toSAFE then requires actualverifiedSTOP readback',async()=>{const f=fixture(),base=f.h.send;await f.c.start(true);let stops=0;f.h.send=async cmd=>cmd==='MOUNT STOP'?(++stops===1?['ERR MOUNT STOP active=0 release_unverified']:['OK MOUNT STOP active=0 torque=off verified=1']):cmd==='SAFE'?['OK SAFE armed=0']:base(cmd);await f.c.stop();assert.equal(f.c.state().busy,false);assert.equal(f.c.state().phase,'idle');assert(stops>=2);});
test('failedSTOP andSAFE retain blockingerror instead of falselyreleased',async()=>{const f=fixture();await f.c.start(true);f.h.send=async()=>{throw Error('port disconnected');};await assert.rejects(f.c.stop(),/断开舵机电源/);assert.equal(f.c.state().busy,true);assert.equal(f.c.state().phase,'error');assert.match(f.c.state().message,/停止未确认/);});

test('softwareinactive andSAFEarmed0 cannot replace sixtorqueverified readback',async()=>{const f=fixture();await f.c.start(true);f.h.send=async cmd=>cmd==='SAFE'?['OK SAFE armed=0']:cmd==='MOUNT STATUS'?['OK MOUNT STATUS active=0']:['OK MOUNT STOP active=0 torque=off'];await assert.rejects(f.c.stop(),/断开舵机电源/);assert.equal(f.c.state().busy,true);assert.equal(f.c.state().phase,'error');assert.equal(f.complete,0);});

test('STS mount uses all six 2048 feedback positions and reported tolerance',async()=>{const f=fixture(),send=f.h.send;f.h.send=async cmd=>(await send(cmd)).map(l=>l.replace(/512/g,'2048')+(l.startsWith('OK MOUNT STATUS')?' profile=STS tolerance=24':''));await f.c.start(true);assert.equal(f.c.state().ready,true);await f.c.finish();assert.equal(f.complete,1);});
test('STS wrong center or missing tolerance cannot unlock installation finish',async()=>{for(const broken of ['target=512','tolerance=6']){const f=fixture(),send=f.h.send;f.h.send=async cmd=>(await send(cmd)).map(l=>{l=l.replace(/512/g,'2048');if(l.startsWith('OK MOUNT STATUS'))l+=' profile=STS tolerance=24';return l.replace(broken.startsWith('target')?'target=2048':'tolerance=24',broken);});await f.c.start(true);assert.equal(f.c.state().ready,false);await f.c.stop();}});
