const test=require('node:test'),assert=require('node:assert/strict');const {controller}=require('../delivery-validation.js');
function fixture(){const sent=[],calls=[],rows=Array.from({length:6},(_,slot)=>({slot,id:slot+1,min:100,max:300,standby:200,press:'min',valid:1}));let connected=true,identity='COM3:1',pose=150;const h={getState:()=>({connected,identity}),send:async cmd=>{sent.push(cmd);if(cmd==='SAFE')return['OK SAFE armed=0'];if(cmd==='INFO')return['OK INFO profile=SCS range=1023'];if(cmd==='CAL STATUS')return [...rows.map(r=>'CAL '+Object.entries(r).map(([k,v])=>k+'='+v).join(' ')),'OK CAL STATUS calibrated=1'];if(cmd.startsWith('SETDIR ')){const [,slot,dir]=cmd.split(' ');rows[+slot].press=dir;rows[+slot].standby=dir==='min'?300:100;return[`OK SETDIR slot=${slot}`];}if(cmd.startsWith('CAL CAPTURE ')){const [,,slot,min,standby,max]=cmd.split(' ');Object.assign(rows[+slot],{min:+min,max:+max,standby:+standby});return[`OK CAL CAPTURE slot=${slot}`];}if(cmd==='CAL SAVE')return['OK CAL SAVE calibrated=1'];if(cmd==='POSALL')return ['OK POSALL '+Array(6).fill(pose).join(' ')];throw Error(cmd);},validate:async opts=>{calls.push(opts);return{completed:true,feedbackVerified:true,fullStroke:true,protocol:'fullStroke-v1',elapsed_ms:4000,feedbackHz:45,feedbackSamples:180};},invalidateCalibration:()=>{},reloadCalibration:async()=>{}};return{h,rows,sent,calls,c:controller(h,{sleep:async()=>{}}),setPose:p=>pose=p,disconnect:()=>connected=false,reconnect:()=>identity='COM3:2'};}
test('direction flip sendsSAFE first, restores midpoint after SETDIR then verifies before SAVE',async()=>{const f=fixture();await f.c.load();f.sent.length=0;await f.c.flip(2);assert.deepEqual(f.sent,['SAFE','SETDIR 2 max','CAL CAPTURE 2 100 200 300','CAL STATUS','CAL SAVE','CAL STATUS']);assert.equal(f.rows[2].standby,200);assert.equal(f.rows[2].press,'max');assert.equal(f.rows[0].press,'min');});
test('all direction application requires explicit choice and does not infer by same exterior',async()=>{const f=fixture();await f.c.load();await assert.rejects(f.c.flipAll(false),/明确/);assert(!f.sent.some(c=>c.startsWith('SETDIR')));await f.c.flipAll(true);assert(f.rows.every(r=>r.press==='max'&&r.standby===200));});
test('manual two stable poses infer selectedslot only',async()=>{const f=fixture();await f.c.load();await f.c.capturePose(3,'release');f.setPose(250);await f.c.capturePose(3,'press');await f.c.applyPose(3);assert.equal(f.rows[3].press,'max');assert(f.rows.filter(r=>r.slot!==3).every(r=>r.press==='min'));});
test('noise sized manualpose cannot decide direction',async()=>{const f=fixture();await f.c.load();await f.c.capturePose(1,'release');f.setPose(152);await f.c.capturePose(1,'press');await assert.rejects(f.c.applyPose(1),/明显不同/);assert(!f.sent.some(c=>c.startsWith('SETDIR')));});
test('five fullstroke levels run only on separate explicitactions, approval never auto drives',async()=>{const f=fixture();await f.c.load();for(const speed of[200,400,600,800,1000]){await f.c.runLevel();assert.equal(f.calls.at(-1).speed,speed);assert.equal(f.calls.at(-1).fullStroke,true);assert.equal(f.calls.at(-1).protocol,'fullStroke-v1');const count=f.calls.length;f.c.accept();assert.equal(f.calls.length,count);}assert.equal(f.c.state().finished,true);assert.equal(f.c.state().history.length,5);});
test('cannot advance before actual completion or runnext without manualapproval',async()=>{const f=fixture();await f.c.load();assert.throws(()=>f.c.accept(),/完成/);await f.c.runLevel();await assert.rejects(f.c.runLevel(),/判断/);assert.equal(f.calls.length,1);});
test('halfstroke oldresults never pass fullstroke protocol',async()=>{const f=fixture();await f.c.load();f.h.validate=async()=>({completed:true,feedbackVerified:true});await assert.rejects(f.c.runLevel(),/完整行程未确认/);assert.equal(f.c.state().result,null);});
test('direction correction or restart invalidates levels without dropping calibrated endpoints',async()=>{const f=fixture();await f.c.load();await f.c.runLevel();f.c.accept();await f.c.flip(0);assert.equal(f.c.state().speed,200);assert.equal(f.c.state().history.length,0);f.sent.length=0;f.c.restart();assert.deepEqual(f.sent,[]);assert.equal(f.rows[0].min,100);assert.equal(f.rows[0].max,300);});
test('changed calibration fingerprint blocks next level before motorcall',async()=>{const f=fixture();await f.c.load();await f.c.runLevel();f.c.accept();f.rows[5].max=290;await assert.rejects(f.c.runLevel(),/行程或方向已变化/);assert.equal(f.calls.length,1);});
test('disconnect cannot trigger level motion',async()=>{const f=fixture();await f.c.load();f.disconnect();await assert.rejects(f.c.runLevel(),/断开/);assert.equal(f.calls.length,0);});
test('failed midpoint capture never commits or falsely reports saved',async()=>{const f=fixture();await f.c.load();const send=f.h.send;f.h.send=async cmd=>cmd.startsWith('CAL CAPTURE ')?['ERR CAL CAPTURE fail']:send(cmd);await assert.rejects(f.c.flip(0),/命令未确认/);assert(!f.sent.includes('CAL SAVE'));});

test('explicit uniform direction applies selecteddirection to all six without guessing',async()=>{const f=fixture();await f.c.load();await assert.rejects(f.c.applyAllDirection('max',false),/明确/);await f.c.applyAllDirection('max',true);assert(f.rows.every(r=>r.press==='max'&&r.standby===200));});
test('approved fullstroke history restores byAP profile range fingerprint across reconnect without motion',async()=>{const f=fixture(),db=new Map();f.h.storage={setItem:(k,v)=>db.set(k,v),getItem:k=>db.get(k)};const send=f.h.send;f.h.send=async cmd=>cmd==='INFO'?['OK INFO profile=SCS range=1023 ap=PIANO_GLOVE_A50528']:send(cmd);await f.c.load();await f.c.runLevel();f.c.accept();f.reconnect();const next=controller(f.h);await next.load();assert.equal(next.state().history.length,1);assert.equal(next.state().speed,400);assert.equal(f.calls.length,1);assert.equal(next.state().history[0].manuallyAccepted,true);});
test('legacy halfstroke or mismatchedcalibration storedresults never restore approval',async()=>{const f=fixture(),db=new Map();f.h.storage={setItem:(k,v)=>db.set(k,v),getItem:k=>db.get(k)};const send=f.h.send;f.h.send=async cmd=>cmd==='INFO'?['OK INFO profile=SCS range=1023 ap=PIANO_GLOVE_A50528']:send(cmd);await f.c.load();await f.c.runLevel();f.c.accept();const key=[...db.keys()][0],record=JSON.parse(db.get(key));record.protocol='halfStroke-v0';db.set(key,JSON.stringify(record));let next=controller(f.h);await next.load();assert.equal(next.state().history.length,0);assert.equal(next.state().speed,200);record.protocol='fullStroke-v1';db.set(key,JSON.stringify(record));f.rows[0].max=280;next=controller(f.h);await next.load();assert.equal(next.state().history.length,0);assert.equal(f.calls.length,1);});

test('STS direction capture uses its encoder scale and separates small noise',async()=>{const f=fixture(),send=f.h.send;f.rows.forEach(r=>Object.assign(r,{min:1000,max:2000,standby:1500}));f.h.send=async cmd=>cmd==='INFO'?['OK INFO profile=STS range=4095 model=3032 bench_speed_unit=counts_per_s']:send(cmd);await f.c.load();f.setPose(1400);await f.c.capturePose(0,'release');f.setPose(1430);await f.c.capturePose(0,'press');await assert.rejects(f.c.applyPose(0),/明显不同/);f.setPose(1800);await f.c.capturePose(0,'press');await f.c.applyPose(0);assert.equal(f.rows[0].press,'max');assert.equal(f.rows[0].standby,1500);});
test('changing model invalidates prior accepted speed history',async()=>{const f=fixture(),db=new Map(),send=f.h.send;let model='modelA';f.h.storage={setItem:(k,v)=>db.set(k,v),getItem:k=>db.get(k)};f.h.send=async cmd=>cmd==='INFO'?[`OK INFO profile=SCS range=1023 ap=board model=${model} bench_speed_unit=counts_per_s`]:send(cmd);await f.c.load();await f.c.runLevel();f.c.accept();model='modelB';const next=controller(f.h);await next.load();assert.equal(next.state().history.length,0);});
